### ISSUE TITLE
Icinga Return value of this check is always 0 "green"

### ISSUE THREAD

**Issue by wadrian-brodos** [NETWAYS/check_sepsesam#4]
Icinga Return value of this check is always 0 "green"

Example:
```
./check_sepsesam.pl -H testhost --lastbackup --outdated 1
2 SEP-Sesam-testhost - CRITICAL: 0 of 1 backups successful with 0 warnings
  sepsesam::check_multi::plugins=1 time=0.00 testhost_backupjob::size=0.00MB tput= durn=0  testhost_backupjob - 'FAILED  Started at: 2019-07-29 18:15:01 Size: 0.00MB'
```

The visual status is "CRITICAL", but the return state is 0 (=OK):
```
echo $?
0
```

The problem is caused in function nagexit.
In the example nagexit errlevel is `2 SEP-Sesam-testhost - CRITICAL`
After line `exit $ERRORS{$errlevel};` the result is ""

As adding and modifying:
```
    $errlevel = substr($errlevel,0,1);
    exit $errlevel;
```

I receive  the correct return value:
```
echo $?
2
```

I dont speak pearl, so my solution is only a workaround and should be fixed from someone with more perl experience.

**Comment by RincewindsHat** [comment]
Edited message for easier reading

**Comment by martialblog** [comment]
The code is definitely buggy. I wonder how this ever worked...
